import * as SQLite from 'expo-sqlite';

import seedData from '@/data/drugs.json';
import { extractKeywords } from '@/db/context-keywords';
import type { Drug, UsageType } from '@/types/drug';

const db = SQLite.openDatabaseSync('pharmasense.db');

let databaseReady = true;
let databaseInitError: string | null = null;

export function getDatabaseInitError(): string | null {
  return databaseInitError;
}

/**
 * Creates tables and, if the drugs table is empty (or the seed file changed),
 * imports the OpenFDA/RxNorm cache generated by scripts/seed-drugs.js.
 * All screens read from this local database — never live APIs.
 */
export function initDatabase(): void {
  try {
    initDatabaseTables();
  } catch (err) {
    databaseReady = false;
    databaseInitError =
      err instanceof Error ? err.message : 'Could not open the local drug database.';
  }
}

function initDatabaseTables(): void {
  db.execSync(`
    PRAGMA journal_mode = WAL;
    CREATE TABLE IF NOT EXISTS drugs (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      drug_class TEXT NOT NULL,
      uses TEXT NOT NULL,
      dosing TEXT NOT NULL,
      side_effects TEXT NOT NULL,
      interactions TEXT NOT NULL,
      notable_fact TEXT NOT NULL,
      otc_or_prescription TEXT NOT NULL CHECK (otc_or_prescription IN ('otc', 'prescription')),
      rxcui TEXT,
      brand_names TEXT NOT NULL DEFAULT ''
    );
    CREATE TABLE IF NOT EXISTS usage (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      type TEXT NOT NULL CHECK (type IN ('search', 'flashcard', 'view', 'ai_query')),
      drug_id INTEGER,
      timestamp INTEGER NOT NULL,
      FOREIGN KEY (drug_id) REFERENCES drugs (id)
    );
    CREATE TABLE IF NOT EXISTS meta (key TEXT PRIMARY KEY, value TEXT NOT NULL);
    CREATE INDEX IF NOT EXISTS idx_usage_type_time ON usage (type, timestamp DESC);
    CREATE INDEX IF NOT EXISTS idx_drugs_name ON drugs (name);
  `);

  // Databases created before RxNorm ids and brand names were stored.
  const columns = new Set(
    db.getAllSync<{ name: string }>(`PRAGMA table_info(drugs)`).map((column) => column.name)
  );
  if (!columns.has('rxcui')) db.execSync(`ALTER TABLE drugs ADD COLUMN rxcui TEXT`);
  if (!columns.has('brand_names')) {
    db.execSync(`ALTER TABLE drugs ADD COLUMN brand_names TEXT NOT NULL DEFAULT ''`);
  }

  const seededVersion = db.getFirstSync<{ value: string }>(
    `SELECT value FROM meta WHERE key = 'seed_version'`
  )?.value;

  if (seededVersion !== seedData.generatedAt) {
    db.withTransactionSync(() => {
      // Keep the user's history across seed refreshes: remember each old id's
      // name, re-import, then point usage rows at the new id for that name.
      db.execSync(`
        DROP TABLE IF EXISTS temp.old_drug_ids;
        CREATE TEMP TABLE old_drug_ids AS SELECT id, name FROM drugs;
      `);
      db.runSync(`DELETE FROM drugs`);
      const insert = db.prepareSync(
        `INSERT INTO drugs (name, drug_class, uses, dosing, side_effects, interactions, notable_fact, otc_or_prescription, rxcui, brand_names)
         VALUES ($name, $drug_class, $uses, $dosing, $side_effects, $interactions, $notable_fact, $otc, $rxcui, $brand_names)`
      );
      try {
        for (const drug of seedData.drugs) {
          insert.executeSync({
            $name: drug.name,
            $drug_class: drug.drug_class,
            $uses: drug.uses,
            $dosing: drug.dosing,
            $side_effects: drug.side_effects,
            $interactions: drug.interactions,
            $notable_fact: drug.notable_fact,
            $otc: drug.otc_or_prescription,
            $rxcui: (drug as { rxcui?: string | null }).rxcui ?? null,
            $brand_names: (drug as { brand_names?: string }).brand_names ?? '',
          });
        }
      } finally {
        insert.finalizeSync();
      }
      // Drugs dropped from the seed keep their usage rows (stats stay) with no drug link.
      db.execSync(`
        UPDATE usage SET drug_id = (
          SELECT d.id FROM drugs d JOIN old_drug_ids o ON o.name = d.name
          WHERE o.id = usage.drug_id
        )
        WHERE drug_id IS NOT NULL;
        DROP TABLE old_drug_ids;
      `);
      db.runSync(
        `INSERT OR REPLACE INTO meta (key, value) VALUES ('seed_version', ?)`,
        [seedData.generatedAt]
      );
    });
  }
}

// ---------- drugs ----------

export function getAllDrugs(): Drug[] {
  if (!databaseReady) return [];
  return db.getAllSync<Drug>(`SELECT * FROM drugs ORDER BY name`);
}

export function getDrugById(id: number): Drug | null {
  if (!databaseReady) return null;
  return db.getFirstSync<Drug>(`SELECT * FROM drugs WHERE id = ?`, [id]) ?? null;
}

export function searchDrugsByName(query: string): Drug[] {
  if (!databaseReady) return [];
  const trimmed = query.trim().replace(/[%_]/g, '');
  if (!trimmed) return [];
  const contains = `%${trimmed}%`;
  const prefix = `${trimmed}%`;
  return db.getAllSync<Drug>(
    `SELECT * FROM drugs
     WHERE name LIKE ? OR drug_class LIKE ? OR brand_names LIKE ?
     ORDER BY CASE WHEN name LIKE ? THEN 0 WHEN brand_names LIKE ? THEN 1 ELSE 2 END, name
     LIMIT 40`,
    [contains, contains, contains, prefix, prefix]
  );
}

export function getDrugCount(): number {
  if (!databaseReady) return 0;
  return db.getFirstSync<{ n: number }>(`SELECT COUNT(*) AS n FROM drugs`)?.n ?? 0;
}

/** Deterministic "Drug of the Day": hashes today's date to a stable index. */
export function getDrugOfTheDay(date: Date = new Date()): Drug | null {
  if (!databaseReady) return null;
  const count = getDrugCount();
  if (count === 0) return null;
  const key = `${date.getFullYear()}-${date.getMonth() + 1}-${date.getDate()}`;
  let hash = 0;
  for (let i = 0; i < key.length; i++) {
    hash = (hash * 31 + key.charCodeAt(i)) >>> 0;
  }
  return db.getFirstSync<Drug>(
    `SELECT * FROM drugs ORDER BY id LIMIT 1 OFFSET ?`,
    [hash % count]
  );
}

/**
 * Finds cached drugs relevant to a free-text message: matches drug names,
 * drug classes, and symptom/use keywords against the uses field.
 * Used to inject grounding context into Ask AI requests.
 */
export function findRelevantDrugs(message: string, limit = 8): Drug[] {
  if (!databaseReady) return [];
  const words = extractKeywords(message);
  if (words.length === 0) return [];

  const found = new Map<number, Drug>();

  // Pass 1: direct drug-name or class mentions (highest priority).
  for (const word of words) {
    const rows = db.getAllSync<Drug>(
      `SELECT * FROM drugs WHERE LOWER(name) LIKE ? OR LOWER(drug_class) LIKE ? LIMIT 5`,
      [`%${word}%`, `%${word}%`]
    );
    for (const row of rows) found.set(row.id, row);
  }

  // Pass 2: symptom keywords matched against the cached "uses" text (OTC only,
  // since symptom questions should ground to OTC categories).
  for (const word of words) {
    if (found.size >= limit) break;
    const rows = db.getAllSync<Drug>(
      `SELECT * FROM drugs WHERE otc_or_prescription = 'otc' AND LOWER(uses) LIKE ? LIMIT 4`,
      [`%${word}%`]
    );
    for (const row of rows) {
      if (found.size >= limit) break;
      found.set(row.id, row);
    }
  }

  return Array.from(found.values()).slice(0, limit);
}

// ---------- usage ----------

export function logUsage(type: UsageType, drugId: number | null = null): void {
  if (!databaseReady) return;
  db.runSync(`INSERT INTO usage (type, drug_id, timestamp) VALUES (?, ?, ?)`, [
    type,
    drugId,
    Date.now(),
  ]);
}

/** Last N distinct drugs with a 'view' usage entry, most recent first. */
export function getRecentlyViewedDrugs(limit = 5): Drug[] {
  if (!databaseReady) return [];
  return db.getAllSync<Drug>(
    `SELECT d.* FROM drugs d
     JOIN (
       SELECT drug_id, MAX(timestamp) AS last_seen FROM usage
       WHERE type = 'view' AND drug_id IS NOT NULL
       GROUP BY drug_id
     ) u ON u.drug_id = d.id
     ORDER BY u.last_seen DESC
     LIMIT ?`,
    [limit]
  );
}

export function getFlashcardsReviewedCount(): number {
  if (!databaseReady) return 0;
  return (
    db.getFirstSync<{ n: number }>(
      `SELECT COUNT(*) AS n FROM usage WHERE type = 'flashcard'`
    )?.n ?? 0
  );
}

export function getAiQueriesThisWeek(): number {
  if (!databaseReady) return 0;
  const weekAgo = Date.now() - 7 * 24 * 60 * 60 * 1000;
  return (
    db.getFirstSync<{ n: number }>(
      `SELECT COUNT(*) AS n FROM usage WHERE type = 'ai_query' AND timestamp >= ?`,
      [weekAgo]
    )?.n ?? 0
  );
}
