// Curated list of common OTC and prescription drugs to seed the local cache.
// `notableFact` is hand-curated because neither OpenFDA nor RxNorm provides
// trivia-style facts. Everything else is fetched from the APIs at seed time.
const DRUG_LIST = [
  // ---- OTC ----
  { name: 'ibuprofen', otc: true, notableFact: 'One of the most widely used NSAIDs in the world, originally discovered in the 1960s as a safer alternative to aspirin.' },
  { name: 'acetaminophen', otc: true, notableFact: 'Known as paracetamol outside the US; overdose is the leading cause of acute liver failure in the United States.' },
  { name: 'aspirin', otc: true, notableFact: 'Derived from willow bark compounds used medicinally for thousands of years; also used in low doses for heart attack prevention.' },
  { name: 'naproxen', otc: true, notableFact: 'Has the longest half-life of common OTC NSAIDs, which is why it can be dosed just twice a day.' },
  { name: 'diphenhydramine', otc: true, notableFact: 'A first-generation antihistamine so sedating that it is also sold as a sleep aid under different brand names.' },
  { name: 'loratadine', otc: true, notableFact: 'A second-generation antihistamine designed to relieve allergies without crossing into the brain and causing drowsiness.' },
  { name: 'cetirizine', otc: true, notableFact: 'A metabolite of the older antihistamine hydroxyzine; slightly more sedating than other second-generation antihistamines.' },
  { name: 'fexofenadine', otc: true, notableFact: 'Fruit juices like orange and grapefruit can significantly reduce its absorption.' },
  { name: 'chlorpheniramine', otc: true, notableFact: 'One of the oldest antihistamines still in wide use, found in many combination cold products.' },
  { name: 'doxylamine', otc: true, notableFact: 'Used both as a nighttime sleep aid and, combined with vitamin B6, as a prescription treatment for morning sickness.' },
  { name: 'famotidine', otc: true, notableFact: 'Became the go-to OTC acid reducer after ranitidine (Zantac) was withdrawn from the market in 2020.' },
  { name: 'omeprazole', otc: true, notableFact: 'The first proton pump inhibitor ever marketed; OTC versions are meant for 14-day courses, not continuous use.' },
  { name: 'esomeprazole', otc: true, notableFact: 'The S-isomer of omeprazole — essentially the mirror-image half of the original molecule.' },
  { name: 'calcium carbonate', otc: true, notableFact: 'Doubles as both an antacid and a calcium supplement; it is the same mineral that makes up chalk and limestone.' },
  { name: 'simethicone', otc: true, notableFact: 'Works purely physically by collapsing gas bubbles in the gut; it is not absorbed into the body at all.' },
  { name: 'loperamide', otc: true, notableFact: 'An opioid that normally cannot cross into the brain, which is why it stops diarrhea without causing euphoria at normal doses.' },
  { name: 'bismuth subsalicylate', otc: true, notableFact: 'Can temporarily and harmlessly turn the tongue and stool black by forming bismuth sulfide.' },
  { name: 'dextromethorphan', otc: true, notableFact: 'Chemically related to opioids but works on different receptors to suppress the cough reflex.' },
  { name: 'guaifenesin', otc: true, notableFact: 'The only expectorant approved by the FDA for OTC use; it originated from the guaiac tree.' },
  { name: 'pseudoephedrine', otc: true, notableFact: 'Sold from behind the pharmacy counter in the US because it can be used to make methamphetamine.' },
  { name: 'phenylephrine', otc: true, notableFact: 'An FDA advisory panel concluded in 2023 that the oral form is ineffective as a decongestant.' },
  { name: 'meclizine', otc: true, notableFact: 'An antihistamine repurposed for motion sickness and vertigo rather than allergies.' },
  { name: 'docusate', otc: true, notableFact: 'A stool softener that works like a detergent, letting water mix into the stool.' },
  { name: 'polyethylene glycol 3350', otc: true, notableFact: 'The same polymer family is used in everything from skin creams to COVID vaccine formulations.' },
  { name: 'bisacodyl', otc: true, notableFact: 'A stimulant laxative that triggers intestinal muscle contractions, typically working within 6 to 12 hours orally.' },
  { name: 'sennosides', otc: true, notableFact: 'Derived from the senna plant, used as a natural laxative since ancient Egyptian times.' },
  { name: 'hydrocortisone', otc: true, notableFact: 'A low-potency version of the stress hormone cortisol your own adrenal glands produce.' },
  { name: 'clotrimazole', otc: true, notableFact: 'A broad-spectrum antifungal used for everything from athlete\u2019s foot to yeast infections.' },
  { name: 'miconazole', otc: true, notableFact: 'Can interact dangerously with the blood thinner warfarin even when used as a topical or vaginal product.' },
  { name: 'benzocaine', otc: true, notableFact: 'A topical anesthetic; the FDA warns against using it in children under 2 due to a rare blood disorder called methemoglobinemia.' },
  // ---- Prescription ----
  { name: 'amoxicillin', otc: false, notableFact: 'A penicillin-family antibiotic and one of the most prescribed drugs for children worldwide.' },
  { name: 'azithromycin', otc: false, notableFact: 'Famous for the 5-day "Z-Pack"; its long tissue half-life means it keeps working for days after the last dose.' },
  { name: 'ciprofloxacin', otc: false, notableFact: 'Carries an FDA boxed warning for tendon rupture, a rare but serious side effect of fluoroquinolones.' },
  { name: 'doxycycline', otc: false, notableFact: 'Can cause severe sunburn-like reactions (photosensitivity) and should not be taken with dairy right at the same time.' },
  { name: 'cephalexin', otc: false, notableFact: 'A first-generation cephalosporin; only a small fraction of penicillin-allergic patients cross-react with it.' },
  { name: 'lisinopril', otc: false, notableFact: 'ACE inhibitors like lisinopril were originally developed from the venom of a Brazilian pit viper.' },
  { name: 'amlodipine', otc: false, notableFact: 'Its very long half-life (30-50 hours) makes it forgiving if a dose is occasionally missed.' },
  { name: 'losartan', otc: false, notableFact: 'The first angiotensin receptor blocker (ARB), often used when ACE inhibitors cause a dry cough.' },
  { name: 'metoprolol', otc: false, notableFact: 'Comes in two salts — tartrate (short-acting) and succinate (long-acting) — that are not interchangeable.' },
  { name: 'atenolol', otc: false, notableFact: 'Unlike most beta blockers, it is cleared by the kidneys rather than the liver.' },
  { name: 'hydrochlorothiazide', otc: false, notableFact: 'One of the oldest blood pressure medicines still in use, introduced in the late 1950s.' },
  { name: 'furosemide', otc: false, notableFact: 'A "loop" diuretic so potent it is nicknamed a water pill on steroids; also used in racehorses.' },
  { name: 'atorvastatin', otc: false, notableFact: 'Sold as Lipitor, it became the best-selling prescription drug in pharmaceutical history.' },
  { name: 'simvastatin', otc: false, notableFact: 'Grapefruit juice can dramatically raise its blood levels and the risk of muscle damage.' },
  { name: 'rosuvastatin', otc: false, notableFact: 'One of the most potent statins per milligram, sometimes called a "super-statin".' },
  { name: 'metformin', otc: false, notableFact: 'Derived from the French lilac plant and used in Europe since the 1950s; first-line therapy for type 2 diabetes.' },
  { name: 'glipizide', otc: false, notableFact: 'A sulfonylurea that stimulates the pancreas to release insulin, so it can cause low blood sugar.' },
  { name: 'levothyroxine', otc: false, notableFact: 'Consistently among the most prescribed drugs in the US; absorption drops if taken with coffee or calcium.' },
  { name: 'sertraline', otc: false, notableFact: 'One of the most prescribed antidepressants in the United States.' },
  { name: 'fluoxetine', otc: false, notableFact: 'Sold as Prozac, it was the first SSRI approved in the US and changed how depression is treated.' },
  { name: 'escitalopram', otc: false, notableFact: 'The purified active isomer of citalopram, allowing lower doses for the same effect.' },
  { name: 'bupropion', otc: false, notableFact: 'The same molecule is marketed both as an antidepressant (Wellbutrin) and a quit-smoking aid (Zyban).' },
  { name: 'duloxetine', otc: false, notableFact: 'Treats depression, anxiety, and nerve pain — a rare triple-duty medication.' },
  { name: 'trazodone', otc: false, notableFact: 'Approved as an antidepressant but far more often prescribed off-label as a sleep aid.' },
  { name: 'alprazolam', otc: false, notableFact: 'Among the most prescribed — and most misused — benzodiazepines in the US.' },
  { name: 'lorazepam', otc: false, notableFact: 'A benzodiazepine short enough acting to be favored in hospitals for acute anxiety and seizures.' },
  { name: 'zolpidem', otc: false, notableFact: 'The FDA halved the recommended dose for women in 2013 after next-morning impairment was documented.' },
  { name: 'gabapentin', otc: false, notableFact: 'Originally designed to mimic the neurotransmitter GABA, but it turned out to work by a completely different mechanism.' },
  { name: 'pregabalin', otc: false, notableFact: 'The successor to gabapentin and a federally controlled substance due to misuse potential.' },
  { name: 'tramadol', otc: false, notableFact: 'A dual-action pain reliever that is part opioid, part antidepressant-like in mechanism.' },
  { name: 'prednisone', otc: false, notableFact: 'A prodrug — the liver must convert it to prednisolone before it becomes active.' },
  { name: 'montelukast', otc: false, notableFact: 'Carries an FDA boxed warning for neuropsychiatric side effects like mood changes.' },
  { name: 'albuterol', otc: false, notableFact: 'The classic rescue inhaler; known as salbutamol in most other countries.' },
  { name: 'warfarin', otc: false, notableFact: 'Started out as a rat poison before becoming the most widely used oral blood thinner of the 20th century.' },
  { name: 'clopidogrel', otc: false, notableFact: 'Some people carry gene variants that prevent them from activating it, making it ineffective.' },
  { name: 'apixaban', otc: false, notableFact: 'A newer blood thinner that, unlike warfarin, requires no routine blood-level monitoring.' },
  { name: 'pantoprazole', otc: false, notableFact: 'A prescription proton pump inhibitor often used intravenously in hospitals for GI bleeding.' },
  { name: 'ondansetron', otc: false, notableFact: 'Developed for chemotherapy nausea; it revolutionized how tolerable cancer treatment is.' },
  { name: 'meloxicam', otc: false, notableFact: 'A prescription NSAID that preferentially targets the COX-2 enzyme at low doses.' },
  { name: 'cyclobenzaprine', otc: false, notableFact: 'Structurally almost identical to the antidepressant amitriptyline, which explains its sedative effects.' },
  { name: 'tamsulosin', otc: false, notableFact: 'Relaxes prostate muscle so selectively it barely affects blood pressure, unlike older alpha blockers.' },
  { name: 'sildenafil', otc: false, notableFact: 'Originally studied as a heart/blood-pressure drug; its famous effect was discovered by accident in clinical trials.' },
  { name: 'spironolactone', otc: false, notableFact: 'A diuretic that blocks aldosterone; also widely used off-label for hormonal acne.' },
];

module.exports = { DRUG_LIST };
