// Curated list of common OTC and prescription drugs to seed the local cache.
// `notableFact` is hand-curated because neither OpenFDA nor RxNorm provides
// trivia-style facts. Everything else is fetched from the APIs at seed time.
const DRUG_LIST = [
  // ---- OTC ----
  { name: 'ibuprofen', otc: true, notableFact: 'One of the most widely used NSAIDs in the world, originally discovered in the 1960s as a safer alternative to aspirin.' },
  { name: 'acetaminophen', otc: true, notableFact: 'Known as paracetamol outside the US; overdose is the leading cause of acute liver failure in the United States.' },
  { name: 'aspirin', otc: true, notableFact: 'Derived from willow bark compounds used medicinally for thousands of years; also used in low doses for heart attack prevention.' },
  { name: 'naproxen', otc: true, notableFact: 'Has the longest half-life of common OTC NSAIDs, which is why it can be dosed just twice a day.' },
  { name: 'diphenhydramine', otc: true, notableFact: 'A first-generation antihistamine so sedating that it is also sold as a sleep aid under different brand names.' },
  { name: 'loratadine', otc: true, notableFact: 'A second-generation antihistamine designed to relieve allergies without crossing into the brain and causing drowsiness.' },
  { name: 'cetirizine', otc: true, notableFact: 'A metabolite of the older antihistamine hydroxyzine; slightly more sedating than other second-generation antihistamines.' },
  { name: 'fexofenadine', otc: true, notableFact: 'Fruit juices like orange and grapefruit can significantly reduce its absorption.' },
  { name: 'chlorpheniramine', otc: true, notableFact: 'One of the oldest antihistamines still in wide use, found in many combination cold products.' },
  { name: 'doxylamine', otc: true, notableFact: 'Used both as a nighttime sleep aid and, combined with vitamin B6, as a prescription treatment for morning sickness.' },
  { name: 'famotidine', otc: true, notableFact: 'Became the go-to OTC acid reducer after ranitidine (Zantac) was withdrawn from the market in 2020.' },
  { name: 'omeprazole', otc: true, notableFact: 'The first proton pump inhibitor ever marketed; OTC versions are meant for 14-day courses, not continuous use.' },
  { name: 'esomeprazole', otc: true, notableFact: 'The S-isomer of omeprazole — essentially the mirror-image half of the original molecule.' },
  { name: 'calcium carbonate', otc: true, notableFact: 'Doubles as both an antacid and a calcium supplement; it is the same mineral that makes up chalk and limestone.' },
  { name: 'simethicone', otc: true, notableFact: 'Works purely physically by collapsing gas bubbles in the gut; it is not absorbed into the body at all.' },
  { name: 'loperamide', otc: true, notableFact: 'An opioid that normally cannot cross into the brain, which is why it stops diarrhea without causing euphoria at normal doses.' },
  { name: 'bismuth subsalicylate', otc: true, notableFact: 'Can temporarily and harmlessly turn the tongue and stool black by forming bismuth sulfide.' },
  { name: 'dextromethorphan', otc: true, notableFact: 'Chemically related to opioids but works on different receptors to suppress the cough reflex.' },
  { name: 'guaifenesin', otc: true, notableFact: 'The only expectorant approved by the FDA for OTC use; it originated from the guaiac tree.' },
  { name: 'pseudoephedrine', otc: true, notableFact: 'Sold from behind the pharmacy counter in the US because it can be used to make methamphetamine.' },
  { name: 'phenylephrine', otc: true, notableFact: 'An FDA advisory panel concluded in 2023 that the oral form is ineffective as a decongestant.' },
  { name: 'meclizine', otc: true, notableFact: 'An antihistamine repurposed for motion sickness and vertigo rather than allergies.' },
  { name: 'docusate', otc: true, notableFact: 'A stool softener that works like a detergent, letting water mix into the stool.' },
  { name: 'polyethylene glycol 3350', otc: true, notableFact: 'The same polymer family is used in everything from skin creams to COVID vaccine formulations.' },
  { name: 'bisacodyl', otc: true, notableFact: 'A stimulant laxative that triggers intestinal muscle contractions, typically working within 6 to 12 hours orally.' },
  { name: 'sennosides', otc: true, notableFact: 'Derived from the senna plant, used as a natural laxative since ancient Egyptian times.' },
  { name: 'hydrocortisone', otc: true, notableFact: 'A low-potency version of the stress hormone cortisol your own adrenal glands produce.' },
  { name: 'clotrimazole', otc: true, notableFact: 'A broad-spectrum antifungal used for everything from athlete\u2019s foot to yeast infections.' },
  { name: 'miconazole', otc: true, notableFact: 'Can interact dangerously with the blood thinner warfarin even when used as a topical or vaginal product.' },
  { name: 'benzocaine', otc: true, notableFact: 'A topical anesthetic; the FDA warns against using it in children under 2 due to a rare blood disorder called methemoglobinemia.' },
  // ---- Prescription ----
  { name: 'amoxicillin', otc: false, notableFact: 'A penicillin-family antibiotic and one of the most prescribed drugs for children worldwide.' },
  { name: 'azithromycin', otc: false, notableFact: 'Famous for the 5-day "Z-Pack"; its long tissue half-life means it keeps working for days after the last dose.' },
  { name: 'ciprofloxacin', otc: false, notableFact: 'Carries an FDA boxed warning for tendon rupture, a rare but serious side effect of fluoroquinolones.' },
  { name: 'doxycycline', otc: false, notableFact: 'Can cause severe sunburn-like reactions (photosensitivity) and should not be taken with dairy right at the same time.' },
  { name: 'cephalexin', otc: false, notableFact: 'A first-generation cephalosporin; only a small fraction of penicillin-allergic patients cross-react with it.' },
  { name: 'lisinopril', otc: false, notableFact: 'ACE inhibitors like lisinopril were originally developed from the venom of a Brazilian pit viper.' },
  { name: 'amlodipine', otc: false, notableFact: 'Its very long half-life (30-50 hours) makes it forgiving if a dose is occasionally missed.' },
  { name: 'losartan', otc: false, notableFact: 'The first angiotensin receptor blocker (ARB), often used when ACE inhibitors cause a dry cough.' },
  { name: 'metoprolol', otc: false, notableFact: 'Comes in two salts — tartrate (short-acting) and succinate (long-acting) — that are not interchangeable.' },
  { name: 'atenolol', otc: false, notableFact: 'Unlike most beta blockers, it is cleared by the kidneys rather than the liver.' },
  { name: 'hydrochlorothiazide', otc: false, notableFact: 'One of the oldest blood pressure medicines still in use, introduced in the late 1950s.' },
  { name: 'furosemide', otc: false, notableFact: 'A "loop" diuretic so potent it is nicknamed a water pill on steroids; also used in racehorses.' },
  { name: 'atorvastatin', otc: false, notableFact: 'Sold as Lipitor, it became the best-selling prescription drug in pharmaceutical history.' },
  { name: 'simvastatin', otc: false, notableFact: 'Grapefruit juice can dramatically raise its blood levels and the risk of muscle damage.' },
  { name: 'rosuvastatin', otc: false, notableFact: 'One of the most potent statins per milligram, sometimes called a "super-statin".' },
  { name: 'metformin', otc: false, notableFact: 'Derived from the French lilac plant and used in Europe since the 1950s; first-line therapy for type 2 diabetes.' },
  { name: 'glipizide', otc: false, notableFact: 'A sulfonylurea that stimulates the pancreas to release insulin, so it can cause low blood sugar.' },
  { name: 'levothyroxine', otc: false, notableFact: 'Consistently among the most prescribed drugs in the US; absorption drops if taken with coffee or calcium.' },
  { name: 'sertraline', otc: false, notableFact: 'One of the most prescribed antidepressants in the United States.' },
  { name: 'fluoxetine', otc: false, notableFact: 'Sold as Prozac, it was the first SSRI approved in the US and changed how depression is treated.' },
  { name: 'escitalopram', otc: false, notableFact: 'The purified active isomer of citalopram, allowing lower doses for the same effect.' },
  { name: 'bupropion', otc: false, notableFact: 'The same molecule is marketed both as an antidepressant (Wellbutrin) and a quit-smoking aid (Zyban).' },
  { name: 'duloxetine', otc: false, notableFact: 'Treats depression, anxiety, and nerve pain — a rare triple-duty medication.' },
  { name: 'trazodone', otc: false, notableFact: 'Approved as an antidepressant but far more often prescribed off-label as a sleep aid.' },
  { name: 'alprazolam', otc: false, notableFact: 'Among the most prescribed — and most misused — benzodiazepines in the US.' },
  { name: 'lorazepam', otc: false, notableFact: 'A benzodiazepine short enough acting to be favored in hospitals for acute anxiety and seizures.' },
  { name: 'zolpidem', otc: false, notableFact: 'The FDA halved the recommended dose for women in 2013 after next-morning impairment was documented.' },
  { name: 'gabapentin', otc: false, notableFact: 'Originally designed to mimic the neurotransmitter GABA, but it turned out to work by a completely different mechanism.' },
  { name: 'pregabalin', otc: false, notableFact: 'The successor to gabapentin and a federally controlled substance due to misuse potential.' },
  { name: 'tramadol', otc: false, notableFact: 'A dual-action pain reliever that is part opioid, part antidepressant-like in mechanism.' },
  { name: 'prednisone', otc: false, notableFact: 'A prodrug — the liver must convert it to prednisolone before it becomes active.' },
  { name: 'montelukast', otc: false, notableFact: 'Carries an FDA boxed warning for neuropsychiatric side effects like mood changes.' },
  { name: 'albuterol', otc: false, notableFact: 'The classic rescue inhaler; known as salbutamol in most other countries.' },
  { name: 'warfarin', otc: false, notableFact: 'Started out as a rat poison before becoming the most widely used oral blood thinner of the 20th century.' },
  { name: 'clopidogrel', otc: false, notableFact: 'Some people carry gene variants that prevent them from activating it, making it ineffective.' },
  { name: 'apixaban', otc: false, notableFact: 'A newer blood thinner that, unlike warfarin, requires no routine blood-level monitoring.' },
  { name: 'pantoprazole', otc: false, notableFact: 'A prescription proton pump inhibitor often used intravenously in hospitals for GI bleeding.' },
  { name: 'ondansetron', otc: false, notableFact: 'Developed for chemotherapy nausea; it revolutionized how tolerable cancer treatment is.' },
  { name: 'meloxicam', otc: false, notableFact: 'A prescription NSAID that preferentially targets the COX-2 enzyme at low doses.' },
  { name: 'cyclobenzaprine', otc: false, notableFact: 'Structurally almost identical to the antidepressant amitriptyline, which explains its sedative effects.' },
  { name: 'tamsulosin', otc: false, notableFact: 'Relaxes prostate muscle so selectively it barely affects blood pressure, unlike older alpha blockers.' },
  { name: 'sildenafil', otc: false, notableFact: 'Originally studied as a heart/blood-pressure drug; its famous effect was discovered by accident in clinical trials.' },
  { name: 'spironolactone', otc: false, notableFact: 'A diuretic that blocks aldosterone; also widely used off-label for hormonal acne.' },
  // ---- Additional OTC (top consumer medicines) ----
  { name: 'lansoprazole', otc: true, notableFact: 'A proton pump inhibitor sold OTC as a 14-day heartburn course, the same class as omeprazole.' },
  { name: 'dimenhydrinate', otc: true, notableFact: 'The classic motion-sickness tablet; it is a combination salt of diphenhydramine and a mild stimulant.' },
  { name: 'oxymetazoline', otc: true, notableFact: 'A nasal decongestant spray that can cause rebound congestion if used more than three days in a row.' },
  { name: 'fluticasone', otc: true, notableFact: 'A corticosteroid used as an allergy nasal spray and, by prescription, as an asthma inhaler.' },
  { name: 'adapalene', otc: true, notableFact: 'A topical retinoid for acne that moved from prescription-only to OTC in the United States.' },
  { name: 'terbinafine', otc: true, notableFact: 'An antifungal that treats athlete’s foot topically and nail fungus when taken by prescription.' },
  { name: 'benzoyl peroxide', otc: true, notableFact: 'Kills acne bacteria by releasing oxygen and can bleach fabric it touches.' },
  { name: 'salicylic acid', otc: true, notableFact: 'A beta hydroxy acid used for acne and warts; chemically related to aspirin.' },
  { name: 'lidocaine', otc: true, notableFact: 'A local anesthetic that numbs tissue by blocking nerve sodium channels; also used by injection in clinics.' },
  { name: 'nicotine', otc: true, notableFact: 'The addictive chemical in tobacco, sold OTC as gum, lozenges, and patches to help people quit smoking.' },
  { name: 'orlistat', otc: true, notableFact: 'A weight-loss drug that blocks fat absorption in the gut; the OTC dose is half the prescription dose.' },
  { name: 'permethrin', otc: true, notableFact: 'A topical insecticide used for head lice and scabies; it is poorly absorbed through skin.' },
  { name: 'psyllium', otc: true, notableFact: 'A soluble fiber from plant husks that works as a bulk-forming laxative and can lower cholesterol modestly.' },
  { name: 'magnesium hydroxide', otc: true, notableFact: 'Sold as milk of magnesia; it neutralizes stomach acid and, in larger amounts, draws water into the bowel.' },
  { name: 'ketotifen', otc: true, notableFact: 'An antihistamine eye drop used for itchy allergic eyes without a prescription in the US.' },
  { name: 'bacitracin', otc: true, notableFact: 'A topical antibiotic ointment used on minor cuts; it is too toxic to give by mouth or injection.' },
  { name: 'minoxidil', otc: true, notableFact: 'Originally a blood-pressure pill; hair growth was a side effect and became its main OTC use.' },
  { name: 'ferrous sulfate', otc: true, notableFact: 'The most common oral iron supplement; it can turn stool dark and is a leading cause of pediatric poisoning.' },
  { name: 'folic acid', otc: true, notableFact: 'A B vitamin recommended before and during early pregnancy to reduce the risk of neural tube defects.' },
  { name: 'cholecalciferol', otc: true, notableFact: 'Vitamin D3, the form skin makes from sunlight; used to prevent and treat vitamin D deficiency.' },
  // ---- Additional prescription (common US outpatient drugs) ----
  { name: 'valsartan', otc: false, notableFact: 'An angiotensin receptor blocker; some lots were recalled in 2018 after a manufacturing impurity was found.' },
  { name: 'olmesartan', otc: false, notableFact: 'An ARB for high blood pressure that rarely causes a severe sprue-like diarrhea.' },
  { name: 'irbesartan', otc: false, notableFact: 'An ARB also studied for protecting kidneys in people with type 2 diabetes and hypertension.' },
  { name: 'benazepril', otc: false, notableFact: 'An ACE inhibitor prodrug the liver converts to its active form, benazeprilat.' },
  { name: 'enalapril', otc: false, notableFact: 'One of the first oral ACE inhibitors; the IV form, enalaprilat, is used in hospitals.' },
  { name: 'ramipril', otc: false, notableFact: 'An ACE inhibitor shown in the HOPE trial to reduce heart attacks in high-risk patients.' },
  { name: 'carvedilol', otc: false, notableFact: 'A beta blocker that also blocks alpha receptors, used for heart failure as well as blood pressure.' },
  { name: 'propranolol', otc: false, notableFact: 'The first successful beta blocker; also used for tremor, migraine prevention, and performance anxiety.' },
  { name: 'bisoprolol', otc: false, notableFact: 'A heart-selective beta blocker commonly used once daily for blood pressure and heart failure.' },
  { name: 'nebivolol', otc: false, notableFact: 'A beta blocker that also releases nitric oxide, which helps blood vessels relax.' },
  { name: 'diltiazem', otc: false, notableFact: 'A calcium channel blocker used for blood pressure, angina, and heart-rate control.' },
  { name: 'verapamil', otc: false, notableFact: 'A calcium channel blocker that slows the heart’s electrical conduction; also used for cluster headache prevention.' },
  { name: 'nifedipine', otc: false, notableFact: 'A calcium channel blocker; the immediate-release form is avoided in emergencies because it can drop blood pressure too fast.' },
  { name: 'clonidine', otc: false, notableFact: 'A blood-pressure drug that works in the brain; stopping it suddenly can cause rebound hypertension.' },
  { name: 'hydralazine', otc: false, notableFact: 'A direct vasodilator often paired with a nitrate for heart failure in patients who cannot take ACE inhibitors.' },
  { name: 'doxazosin', otc: false, notableFact: 'An alpha blocker used for both high blood pressure and urinary symptoms from an enlarged prostate.' },
  { name: 'chlorthalidone', otc: false, notableFact: 'A thiazide-like diuretic that lasts longer than hydrochlorothiazide and is often preferred for hypertension.' },
  { name: 'digoxin', otc: false, notableFact: 'Derived from the foxglove plant; it has a narrow safety margin and levels are affected by kidney function.' },
  { name: 'amiodarone', otc: false, notableFact: 'A powerful heart-rhythm drug that can affect the thyroid, lungs, liver, and skin with long-term use.' },
  { name: 'nitroglycerin', otc: false, notableFact: 'The same chemical as the explosive, used in tiny doses to open heart blood vessels during angina.' },
  { name: 'isosorbide mononitrate', otc: false, notableFact: 'A long-acting nitrate for angina prevention; a daily nitrate-free interval helps it keep working.' },
  { name: 'rivaroxaban', otc: false, notableFact: 'A once-daily oral blood thinner that blocks clotting factor Xa and needs no routine INR checks.' },
  { name: 'dabigatran', otc: false, notableFact: 'The first widely used oral direct thrombin inhibitor, an alternative to warfarin for atrial fibrillation.' },
  { name: 'pravastatin', otc: false, notableFact: 'A statin less dependent on liver CYP3A4, so it has fewer interactions with common drugs than simvastatin.' },
  { name: 'lovastatin', otc: false, notableFact: 'The first statin approved in the US, originally isolated from a fungus.' },
  { name: 'ezetimibe', otc: false, notableFact: 'Lowers cholesterol by blocking absorption in the intestine, a different mechanism from statins.' },
  { name: 'fenofibrate', otc: false, notableFact: 'A fibrate used mainly to lower triglycerides rather than LDL cholesterol.' },
  { name: 'glimepiride', otc: false, notableFact: 'A once-daily sulfonylurea that pushes the pancreas to release more insulin and can cause low blood sugar.' },
  { name: 'sitagliptin', otc: false, notableFact: 'A DPP-4 inhibitor for type 2 diabetes that rarely causes low blood sugar when used alone.' },
  { name: 'empagliflozin', otc: false, notableFact: 'An SGLT2 inhibitor that spills glucose into urine and also reduces heart-failure hospitalizations.' },
  { name: 'dapagliflozin', otc: false, notableFact: 'An SGLT2 inhibitor used for type 2 diabetes, heart failure, and chronic kidney disease.' },
  { name: 'pioglitazone', otc: false, notableFact: 'A thiazolidinedione that improves insulin sensitivity; it can cause fluid retention.' },
  { name: 'insulin glargine', otc: false, notableFact: 'A long-acting insulin designed to last about 24 hours with a relatively flat effect.' },
  { name: 'semaglutide', otc: false, notableFact: 'A GLP-1 medicine used for type 2 diabetes and, at a higher dose, for chronic weight management.' },
  { name: 'liraglutide', otc: false, notableFact: 'A daily GLP-1 injection that was among the first in its class to show cardiovascular benefit.' },
  { name: 'methimazole', otc: false, notableFact: 'The preferred antithyroid pill in the US for hyperthyroidism, except early in pregnancy.' },
  { name: 'diclofenac', otc: false, notableFact: 'An NSAID available as tablets, gels, and eye drops; oral use carries the usual NSAID heart and stomach risks.' },
  { name: 'celecoxib', otc: false, notableFact: 'A COX-2 selective NSAID designed to cause less stomach irritation than older NSAIDs.' },
  { name: 'oxycodone', otc: false, notableFact: 'A potent opioid pain medicine and a major driver of the US opioid overdose epidemic.' },
  { name: 'morphine', otc: false, notableFact: 'The original opioid, isolated from opium poppies; most other opioids are compared against it.' },
  { name: 'clonazepam', otc: false, notableFact: 'A long-acting benzodiazepine used for panic disorder and certain seizure types.' },
  { name: 'diazepam', otc: false, notableFact: 'Sold as Valium, one of the first benzodiazepines; it has active metabolites that linger for days.' },
  { name: 'buspirone', otc: false, notableFact: 'An anxiety medicine that is not a benzodiazepine and is not sedating or addictive in the same way.' },
  { name: 'hydroxyzine', otc: false, notableFact: 'An older antihistamine prescribed for itching and anxiety; cetirizine is its active metabolite.' },
  { name: 'citalopram', otc: false, notableFact: 'An SSRI whose dose is limited because higher doses can prolong the heart’s QT interval.' },
  { name: 'paroxetine', otc: false, notableFact: 'An SSRI more likely than others in its class to cause withdrawal symptoms if stopped abruptly.' },
  { name: 'venlafaxine', otc: false, notableFact: 'An SNRI antidepressant; missing a dose often causes a brief “brain zap” withdrawal feeling.' },
  { name: 'mirtazapine', otc: false, notableFact: 'An antidepressant that often increases appetite and sleepiness, so it is used when those effects are helpful.' },
  { name: 'amitriptyline', otc: false, notableFact: 'An older tricyclic antidepressant now used more often for nerve pain and migraine prevention.' },
  { name: 'nortriptyline', otc: false, notableFact: 'The active metabolite of amitriptyline, usually less sedating than the parent drug.' },
  { name: 'quetiapine', otc: false, notableFact: 'An antipsychotic also widely prescribed at low doses for sleep, though that use is controversial.' },
  { name: 'aripiprazole', otc: false, notableFact: 'An antipsychotic that partially activates dopamine receptors instead of fully blocking them.' },
  { name: 'risperidone', otc: false, notableFact: 'An antipsychotic that can raise prolactin and cause breast tenderness or missed periods.' },
  { name: 'olanzapine', otc: false, notableFact: 'An effective antipsychotic that commonly causes significant weight gain and metabolic changes.' },
  { name: 'lamotrigine', otc: false, notableFact: 'A seizure and bipolar medicine that must be started slowly to reduce the risk of a serious rash.' },
  { name: 'levetiracetam', otc: false, notableFact: 'A widely used seizure medicine with few drug interactions but occasional irritability as a side effect.' },
  { name: 'topiramate', otc: false, notableFact: 'Used for seizures and migraine prevention; it can cause tingling, word-finding trouble, and weight loss.' },
  { name: 'divalproex', otc: false, notableFact: 'A valproate used for seizures, bipolar disorder, and migraine; it is dangerous in pregnancy.' },
  { name: 'carbamazepine', otc: false, notableFact: 'An older seizure and nerve-pain drug that induces many liver enzymes and lowers levels of other medicines.' },
  { name: 'sumatriptan', otc: false, notableFact: 'The first triptan, designed to stop a migraine by tightening dilated cranial blood vessels.' },
  { name: 'donepezil', otc: false, notableFact: 'A cholinesterase inhibitor used to slow symptoms of Alzheimer disease, not to cure it.' },
  { name: 'memantine', otc: false, notableFact: 'An Alzheimer medicine that blocks NMDA glutamate receptors, often added to donepezil.' },
  { name: 'pramipexole', otc: false, notableFact: 'A dopamine agonist used for Parkinson disease and restless legs syndrome.' },
  { name: 'ropinirole', otc: false, notableFact: 'A dopamine agonist that can cause sudden sleepiness and impulse-control problems.' },
  { name: 'methylphenidate', otc: false, notableFact: 'A stimulant used for ADHD; it is a controlled substance with many short- and long-acting forms.' },
  { name: 'lisdexamfetamine', otc: false, notableFact: 'A prodrug of dextroamphetamine designed so it cannot be activated as quickly if injected or snorted.' },
  { name: 'dextroamphetamine', otc: false, notableFact: 'The more active half of amphetamine, used for ADHD and narcolepsy.' },
  { name: 'atomoxetine', otc: false, notableFact: 'A non-stimulant ADHD medicine that works on norepinephrine and is not a controlled substance.' },
  { name: 'baclofen', otc: false, notableFact: 'A muscle relaxant that mimics GABA in the spinal cord; stopping high doses suddenly can cause withdrawal.' },
  { name: 'tizanidine', otc: false, notableFact: 'A short-acting muscle relaxant that can drop blood pressure and interacts with ciprofloxacin.' },
  { name: 'allopurinol', otc: false, notableFact: 'Lowers uric acid to prevent gout flares; starting it during an acute flare used to be avoided, but that practice has changed.' },
  { name: 'colchicine', otc: false, notableFact: 'An ancient gout drug from the autumn crocus; the therapeutic dose is close to the dose that causes severe diarrhea.' },
  { name: 'metronidazole', otc: false, notableFact: 'An antibiotic for anaerobic bacteria and some parasites; alcohol can cause a unpleasant reaction with it.' },
  { name: 'clindamycin', otc: false, notableFact: 'An antibiotic with a well-known risk of C. difficile diarrhea.' },
  { name: 'nitrofurantoin', otc: false, notableFact: 'A urinary antibiotic that concentrates in urine and is a first-line option for uncomplicated bladder infections.' },
  { name: 'cefdinir', otc: false, notableFact: 'An oral cephalosporin often used for ear, sinus, and skin infections; iron supplements can block its absorption.' },
  { name: 'levofloxacin', otc: false, notableFact: 'A fluoroquinolone antibiotic that shares the class boxed warnings for tendons, nerves, and the aorta.' },
  { name: 'fluconazole', otc: false, notableFact: 'An oral antifungal often given as a single dose for vaginal yeast infections.' },
  { name: 'acyclovir', otc: false, notableFact: 'The first widely used antiviral for herpes viruses; it must be started early in an outbreak to help most.' },
  { name: 'valacyclovir', otc: false, notableFact: 'A prodrug the body converts to acyclovir, allowing fewer doses per day.' },
  { name: 'oseltamivir', otc: false, notableFact: 'An antiviral that shortens influenza if started within about 48 hours of symptoms.' },
  { name: 'cefuroxime', otc: false, notableFact: 'A second-generation cephalosporin used for respiratory and some skin infections.' },
  { name: 'budesonide', otc: false, notableFact: 'A corticosteroid used in inhalers for asthma and in gut-targeted forms for inflammatory bowel disease.' },
  { name: 'tiotropium', otc: false, notableFact: 'A long-acting inhaled anticholinergic that is a mainstay maintenance inhaler for COPD.' },
  { name: 'ipratropium', otc: false, notableFact: 'A short-acting inhaled anticholinergic used as a bronchodilator, often with albuterol in the ER.' },
  { name: 'benzonatate', otc: false, notableFact: 'A prescription cough capsule that numbs stretch receptors in the lungs; chewing it can numb the mouth and throat dangerously.' },
  { name: 'prednisolone', otc: false, notableFact: 'The active form of prednisone, often used as a liquid for children who cannot swallow tablets.' },
  { name: 'methylprednisolone', otc: false, notableFact: 'A corticosteroid often given as a tapered “dose pack” for short inflammatory flares.' },
  { name: 'dexamethasone', otc: false, notableFact: 'A potent, long-acting corticosteroid used for inflammation, nausea, and brain swelling.' },
  { name: 'mometasone', otc: false, notableFact: 'A corticosteroid used in nasal sprays and skin creams with relatively low absorption into the bloodstream.' },
  { name: 'sucralfate', otc: false, notableFact: 'Forms a protective coating over ulcers; it is barely absorbed but can bind other medicines in the stomach.' },
  { name: 'finasteride', otc: false, notableFact: 'Blocks conversion of testosterone to DHT; a low dose is used for hair loss and a higher dose for prostate enlargement.' },
  { name: 'tadalafil', otc: false, notableFact: 'A PDE5 inhibitor known for a much longer duration than sildenafil; also used daily for urinary symptoms.' },
  { name: 'oxybutynin', otc: false, notableFact: 'An anticholinergic used for overactive bladder that commonly causes dry mouth.' },
  { name: 'mirabegron', otc: false, notableFact: 'Relaxes the bladder by stimulating beta-3 receptors, an alternative to anticholinergic bladder drugs.' },
  { name: 'latanoprost', otc: false, notableFact: 'A glaucoma eye drop that lowers eye pressure and can gradually darken the iris.' },
  { name: 'estradiol', otc: false, notableFact: 'The main estrogen the body makes before menopause, replaced with pills, patches, or gels when levels fall.' },
  { name: 'norethindrone', otc: false, notableFact: 'A progestin used in birth control and to regulate menstrual bleeding.' },
  { name: 'anastrozole', otc: false, notableFact: 'An aromatase inhibitor that lowers estrogen and is used for hormone-receptor-positive breast cancer.' },
  { name: 'tamoxifen', otc: false, notableFact: 'A selective estrogen receptor modulator used for decades to treat and reduce the risk of breast cancer.' },
  { name: 'alendronate', otc: false, notableFact: 'A weekly bisphosphonate for osteoporosis that must be taken upright with plain water so it does not irritate the esophagus.' },
  { name: 'methotrexate', otc: false, notableFact: 'Used weekly in low doses for rheumatoid arthritis and in much higher doses for some cancers.' },
  { name: 'hydroxychloroquine', otc: false, notableFact: 'An antimalarial also used for lupus and rheumatoid arthritis; long-term use needs eye monitoring.' },
  { name: 'potassium chloride', otc: false, notableFact: 'Replaces potassium lost from diuretics; tablets can irritate the stomach if not taken as directed.' },
  { name: 'naltrexone', otc: false, notableFact: 'Blocks opioid receptors and is used for alcohol use disorder and opioid use disorder.' },
  { name: 'varenicline', otc: false, notableFact: 'A quit-smoking pill that partially stimulates nicotine receptors while blocking nicotine from cigarettes.' },
  { name: 'timolol', otc: false, notableFact: 'A beta blocker eye drop for glaucoma that can still slow the heart or worsen asthma in sensitive people.' },
];

module.exports = { DRUG_LIST };
